### ISSUE TITLE
Exemple subclass

### ISSUE THREAD

**Issue by LilNesquuik** [steven4547466/Advanced-Subclassing-Redux#11]
can i get .yml exemple ? for subclass

**Comment by iojforever** [comment]
[example.txt](https://github.com/steven4547466/Advanced-Subclassing-Redux/files/8966720/example.txt)

Change `.txt` into `.yml`. 
Github wont let me to send `.yml` since its unsupported.
Also, everything about how to create a subclass included into A-S-R releases.
So please, close that issue asap. @Moxii0307

**Comment by steven4547466** [comment]
Resolved above.
